AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'proxy-request-service'

Resources:
  ProxyRequestService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.handle_event
      Runtime: ruby2.5
      Timeout: 10
      Environment:
        Variables:
          SQS_QUEUE_URL: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJ8wgZwGCSqGSIb3DQEHBqCBjjCBiwIBADCBhQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyGzmQLgDBtSUal/G0CARCAWCPYxUwBOm/dzWVt+72KuNd38rXxzccgc8SJWnWNwVaOzLl1iecDiMEfu5Y6qilQ/0auMpVMf0DJ6R4HEHi5woTQB8l8npfqEVATzZ6aP/YhSP5kPpdW0Qk=
          LOG_LEVEL: debug
