AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'proxy-request-service'

Resources:
  SyncItemMetadataToScsbService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: application.handle_event
      Runtime: ruby2.5
      Timeout: 10
      Environment:
        Variables:
          SQS_QUEUE_URL: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAKowgacGCSqGSIb3DQEHBqCBmTCBlgIBADCBkAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAyf5SLN3bvMXtB5EjUCARCAYwQA44aMtSMj/VLHQB4/lPny0WMivTWtwN5tusjrNAJjlCAI/PW9F98y3HrAdH4lJI7KEMfe43Ex1u57Jx5YI/bBFQKlTyGat7mnyFOIRUOVGH7TqtOeXQ1M6FTMlAbWP67/bQ==
          LOG_LEVEL: debug
